version: '3'
services:

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - 27017

  webstrates:
    container_name: webstrates
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
    ports:
      - 80:80
